version: '3.8'
services:
  app:
    image: openjdk:17-jdk-alpine
    container_name: music
    working_dir: /app
    volumes:
      - ./:/app
    command: ["./mvnw", "spring-boot:run"]
    ports:  
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on: []
# Add database or other services below as needed
# Example for PostgreSQL:
#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: bigschema
#    ports:
#      - "5432:5432"
